version: "3"
services:
  development:
    build: .
    container_name: landing-maker
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - ENV=development
      - PORT=80
    ports:
      - '8080:80'
    command: npm start
